apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-appsets
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default
  source:
    repoURL: git@github.com:bobbykim-nsuslab/multi-cluster-argo-demo.git
    targetRevision: main
    path: applicationsets/v1.25
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}